apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - etl-ingest
      containers:
      - name: data-ingestion
        image: harshwardhan19/data-ingestion:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion
spec:
  selector:
    app: data-ingestion
  ports:
  - protocol: TCP
    port: 8004
    targetPort: 8004
  type: ClusterIP
