apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - etl-ingest
      containers:
      - name: data-ingestion
        image: data-ingestion:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion
spec:
  selector:
    app: data-ingestion
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
  type: ClusterIP
